//export { default as AdminGroups } from './AdminGroups/AdminGroups.vue'
export { default as AdminGroups } from './admin/AdminGroups/AdminGroups.vue'
export { default as TeacherGroups } from './TeacherGroups/TeacherGroups.vue'
//export { default as StudentGroups } from './StudentGroups/StudentGroups.vue'
export { default as StudentGroups } from './student/StudentGroups/StudentGroups.vue'
export { type IGroupUsers } from './types'
export { type IGroupInfo } from './types'
